# Generated by Django 5.0.3 on 2024-04-05 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_categories_options_alter_categories_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Poducts',
            new_name='Products',
        ),
    ]
